name: 'Build With Muddler'
description: 'Build your Mudlet project using muddler'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  muddler-version:
    description: 'Version of muddler to use'
    required: false
    default: '0.5'
runs:
  using: "composite"      
    run: ${{ github.action_path }}/muddle.sh
    shell: bash
