name: 'Build With Muddler'
description: 'Build your Mudlet project using muddler'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  package-name:
    description: 'Name of the package to upload'
    required: true
  muddler-version:
    description: 'Version of muddler to use'
    required: false
    default: '0.5'
runs:
  using: "composite"      
    - name: Retrieve muddler
      run: |
        curl -L https://github.com/demonnic/muddler/releases/download/0.5/muddle-shadow-$INPUT_.tar --output muddler.tar
        mkdir muddler-tmp
        tar xf muddler.tar -C muddler-tmp
        mv muddler-tmp/muddle-shadow-${{ inputs.muddler-version }} muddler
        rm -rf muddler-tmp muddler.tar
      shell: bash
      
    - name: Build package with muddler
      run: |
        muddler/bin/muddle
      shell: bash
