name: 'Build With Muddler'
description: 'Build your Mudlet project using muddler'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  muddlerVersion:
    description: 'Version of muddler to use'
    required: false
    default: 'LATEST'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/muddle.sh ${{ inputs.muddlerVersion }}
      shell: bash
